# This is the docker-compose.yml file for setting up the application stack.
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/servicedb
    depends_on:
      - db

  db:
    image: postgis/postgis:13-3.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=servicedb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
